version: '3.9'
services:
  db:
    image: postgres:latest
    container_name: recom_postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=recom
    volumes:
      - recom-db-data:/var/lib/postgresql/data/

volumes:
  recom-db-data:
